### ISSUE TITLE
ATX headings without following empty line get rendered wrong

### ISSUE THREAD

**Issue by MrEbbinghaus** [askonomm/clarktown#13]
Following Markdown:

```markdown
### Composition
You may have noticed the line with the note: _Where to begin the query?_
In our application, we have _one_ normalized-state. So we want _one_ query to get _one_ tree to pass to our render function. 

Coming back to our complete code from before, we can replace the `person` function with our component:
```

gets rendered like: 
![image](https://user-images.githubusercontent.com/2965273/163154627-7e3524a1-e457-4f3e-b988-128acdb74e87.png)

(Note: the ticks around `person` are part of my stylesheet, it is not a bug.)

**Comment by askonomm** [comment]
This happens for the same reason as #14 happens, to quote a reply I made there:

> This is by design. Clarktown parses blocks, and blocks are created by having two line breaks in-between. Thus, your example is just one block of text as far as Clarktown is concerned and not two different ones. And since the block starts with regular text, it determines it's just a paragraph and not a code block, which starts with with the uptick characters. You really want to have two line breaks between blocks.
> 
> To make this work would require some significant rewrite of the underlying architecture as the whole premise is built under the idea that blocks are separated by two newlines.

**Comment by askonomm** [comment]
On further thought, I think I might be able to figure out a way with the a _slight_ architecture change to make this work. I'll see if I can do it the coming weekend. Same goes for #14.
